/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orpis;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class form1 extends javax.swing.JFrame {
public LogIn login=new LogIn();
int storeid_extracted=login.getStore();
int roleid_extracted=login.getRole();
    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        view_user = new javax.swing.JButton();
        edit_user = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        dob = new com.toedter.calendar.JDateChooser();
        mobile = new javax.swing.JTextField();
        roles = new javax.swing.JComboBox<>();
        stores = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Email id:");

        jLabel4.setText("Address:");

        jLabel5.setText("Mobile:");

        jLabel6.setText("Date of birth:");

        jLabel7.setText("Role:");

        jLabel8.setText("Store:");

        view_user.setText("View User");
        view_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_userActionPerformed(evt);
            }
        });

        edit_user.setText("Edit User");
        edit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_userActionPerformed(evt);
            }
        });

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        add.setColumns(20);
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customer", "Employee", "Store Admin" }));

        stores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brandon", "CALGARY", "EDMONTON", "HALIFAX", "HAMILTON", "LONDON", "NW CALGARY", "OTTAWA", "REGINA", "SASKATOON", "SUDBURY", "WINNIPEG", " " }));

        jLabel9.setText("Search user by mobile number!");

        jLabel10.setText("Search user by mobile number!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fname)
                            .addComponent(lname)
                            .addComponent(email)
                            .addComponent(jScrollPane1)
                            .addComponent(mobile)
                            .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(view_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit_user)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(stores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_user)
                    .addComponent(edit_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void view_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_userActionPerformed
        try {
            Connection conn=null;
            conn=ConnectionManager.getConnection();
            String mob_no=mobile.getText();
            String query1="select uName,ulName,uStore,dob,address,uEmail,uRole from tbl_allusers where uMobile=?";
            int roleid,storeid;
            String rolename,storename;
            PreparedStatement pst1=conn.prepareStatement(query1);
            pst1.setString(1,mob_no);
            ResultSet rs1=pst1.executeQuery();
            if(rs1.next()){
                roleid=rs1.getInt("uRole");
                storeid=rs1.getInt("uStore");
                if(roleid_extracted==1 || (roleid_extracted==2 && storeid_extracted==storeid)){
                String query2="select roleName from tbl_roles where roleId=?";
                PreparedStatement pst2=conn.prepareStatement(query2);
                pst2.setInt(1,roleid);
                String query3="select name from tbl_stores where storeId=?";
                PreparedStatement pst3=conn.prepareStatement(query3);
                pst3.setInt(1,storeid);
                ResultSet rs2=pst2.executeQuery();
                ResultSet rs3=pst3.executeQuery();
                if(rs2.next()==true && rs3.next()==true){
                    rolename=rs2.getString("roleName");
                    storename=rs3.getString("name");
                    fname.setText(rs1.getString("uName"));
                    lname.setText(rs1.getString("ulName"));
                    email.setText(rs1.getString("uEmail"));
                    add.setText(rs1.getString("address"));
                    roles.setSelectedItem(rolename);
                    stores.setSelectedItem(storename);
                    dob.setDate(rs1.getDate("dob"));
                }
                }
                else if(roleid_extracted==2 && storeid_extracted!=storeid){
                    JOptionPane.showMessageDialog(this,"You don't have the access to this store details");
                }  
            }
            
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(form1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(form1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_view_userActionPerformed

    private void edit_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_userActionPerformed
        try {
            // TODO add your handling code here:
            Connection conn=null;
            conn=ConnectionManager.getConnection();
            PreparedStatement pst1,pst2,pst3,pst4;
            ResultSet rs1,rs2,rs4;
            String role=roles.getSelectedItem().toString();
            String store=stores.getSelectedItem().toString();
            String query1="select storeId from tbl_stores where name=?";
            String query2="select roleId from tbl_roles where roleName=?";
            String query4="select uEmail from tbl_allusers";
            pst1=conn.prepareStatement(query1);
            pst2=conn.prepareStatement(query2);
            pst4=conn.prepareStatement(query4);
            pst1.setString(1,store);
            pst2.setString(1, role);
            int storeid=0;
            int roleid=0;
            rs2=pst2.executeQuery();
            rs1=pst1.executeQuery();
            rs4=pst4.executeQuery();
            int count=0;
            while(rs4.next()){
                String stringToCompare=rs4.getString("uEmail");
                if(email.getText().equals(stringToCompare)){
                    count++;
                }
            }
            if(rs1.next()==true && rs2.next()==true ){
                storeid=rs1.getInt(1);
                roleid=rs2.getInt(1);
                //emailid=rs4.getString("uEmail");
            }
            if(count==0 && (roleid_extracted==1 || (roleid_extracted==2 && storeid_extracted==storeid))){
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
                java.util.Date d1=dob.getDate();
                String newDate=formatter.format(d1);
                String query3="update tbl_allusers set uName=?,ulName=?,uStore=?,dob=?,address=?,uEmail=?,uRole=? where uMobile=?";
                pst3=conn.prepareStatement(query3);
                pst3.setString(1,fname.getText());
                pst3.setString(2,lname.getText());
                pst3.setInt(3,storeid);
                pst3.setDate(4,java.sql.Date.valueOf(newDate));
                pst3.setString(5,add.getText());
                
                //JOptionPane.showMessageDialog(this,"email id already exists");
                
                
                pst3.setString(6,email.getText());
                
                pst3.setInt(7,roleid);
                pst3.setString(8,mobile.getText());
                pst3.executeUpdate();
                JOptionPane.showMessageDialog(this,"updated");
                
            }
            else if(roleid_extracted==2 && storeid!=storeid_extracted){
                JOptionPane.showMessageDialog(this,"You don't have the access to this store details");
            }
             else{
                JOptionPane.showMessageDialog(this,"email id already exists");
            }
            
        }
        
            catch (ClassNotFoundException ex) {
            Logger.getLogger(form1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(form1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edit_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JButton edit_user;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mobile;
    private javax.swing.JComboBox<String> roles;
    private javax.swing.JComboBox<String> stores;
    private javax.swing.JButton view_user;
    // End of variables declaration//GEN-END:variables
}
